class AppConfig

  # ACTION RELATED
  ACTION_TOTAL_AP 		= 10;
  
  ACTION_COST_USE     	= 2
  ACTION_COST_KILL    	= 5
  ACTION_COST_REPAIR  	= 2
  ACTION_COST_MOVE    	= 1
  ACTION_COST_INITVOTE	= 2
  ACTION_COST_VOTE    	= 5
  ACTION_COST_STATUS  	= 2
  
  # WATER RELATED
  WATER_CONSUMED_PER_PERSON = 50
  WATER_UNIT			= "litre"
  WATER_FULL_TANK		= 1000
  
  
end